/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.thuthu.seamlyhem

import kotlin.test.Test

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
    }
}
